interface OpeanSeaContract {
  collection: {
    slug: string;
    [key: string]: any;
  };
  [key: string]: any;
}

interface OpeanSeaCollection {
  collection: {
    slug: string;
    [key: string]: any;
  };
  [key: string]: any;
}
export namespace fakeReponses {
  export class OpenSea {
    ContractData(): OpeanSeaContract {
      return {
        collection: {
          banner_image_url: 'https://i.seadn.io/gcs/files/922091e27631ca5039e80b5d12707a37.jpg?w=500&auto=format',
          chat_url: null,
          created_date: '2022-12-02T02:48:03.907050+00:00',
          default_to_fiat: false,
          description: 'Always VEE yourself.',
          dev_buyer_fee_basis_points: '0',
          dev_seller_fee_basis_points: '750',
          discord_url: null,
          display_data: {
            card_display_style: 'cover',
            images: null
          },
          external_url: 'https://bevee.club',
          featured: false,
          featured_image_url: 'https://i.seadn.io/gcs/files/c8696d3a112d150f11703eba27e12e76.jpg?w=500&auto=format',
          hidden: false,
          safelist_request_status: 'not_requested',
          image_url: 'https://i.seadn.io/gcs/files/acac3af5552e20c82fc031e394a8b742.gif?w=500&auto=format',
          is_subject_to_whitelist: false,
          large_image_url: 'https://i.seadn.io/gcs/files/c8696d3a112d150f11703eba27e12e76.jpg?w=500&auto=format',
          medium_username: null,
          name: 'Be VEE - VEE Collection',
          only_proxied_transfers: false,
          opensea_buyer_fee_basis_points: '0',
          opensea_seller_fee_basis_points: '250',
          payout_address: '0x2201f580067ff833b25233da236a0f5b31dbfc96',
          require_email: false,
          short_description: null,
          slug: 'be-vee-vee-collection',
          telegram_url: null,
          twitter_username: 'BeVEENFT',
          instagram_username: null,
          wiki_url: null,
          is_nsfw: false,
          fees: {
            seller_fees: {
              '0x2201f580067ff833b25233da236a0f5b31dbfc96': 750
            },
            opensea_fees: {
              '0x0000a26b00c1f0df003000390027140000faa719': 250
            }
          },
          is_rarity_enabled: true
        },
        address: '0x2e35e63808b3fc6923a4097c22f3f14f983d78d7',
        asset_contract_type: 'non-fungible',
        created_date: '2022-12-02T02:30:02.255452',
        name: 'Be VEE - VEE Collection',
        nft_version: '3.0',
        opensea_version: null,
        owner: 536390166,
        schema_name: 'ERC721',
        symbol: 'VEE',
        total_supply: '0',
        description: 'Always VEE yourself.',
        external_link: 'https://bevee.club',
        image_url: 'https://i.seadn.io/gcs/files/acac3af5552e20c82fc031e394a8b742.gif?w=500&auto=format',
        default_to_fiat: false,
        dev_buyer_fee_basis_points: 0,
        dev_seller_fee_basis_points: 750,
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: 0,
        opensea_seller_fee_basis_points: 250,
        buyer_fee_basis_points: 0,
        seller_fee_basis_points: 1000,
        payout_address: '0x2201f580067ff833b25233da236a0f5b31dbfc96'
      };
    }
    CollectionData(): OpeanSeaCollection {
      return {
        collection: {
          editors: ['0x2b3ab8e7bb14988616359b78709538b10900ab7d'],
          payment_tokens: [
            {
              id: 13689077,
              symbol: 'ETH',
              address: '0x0000000000000000000000000000000000000000',
              image_url: 'https://openseauserdata.com/files/6f8e2979d428180222796ff4a33ab929.svg',
              name: 'Ether',
              decimals: 18,
              eth_price: 1,
              usd_price: 1210.64
            },
            {
              id: 4645681,
              symbol: 'WETH',
              address: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
              image_url: 'https://openseauserdata.com/files/accae6b6fb3888cbff27a013729c22dc.svg',
              name: 'Wrapped Ether',
              decimals: 18,
              eth_price: 1,
              usd_price: 1210.64
            }
          ],
          primary_asset_contracts: [
            {
              address: '0x8a90cab2b38dba80c64b7734e58ee1db38b8992e',
              asset_contract_type: 'non-fungible',
              created_date: '2021-10-16T16:25:03.736944',
              name: 'Doodles',
              nft_version: '3.0',
              opensea_version: null,
              owner: 96236530,
              schema_name: 'ERC721',
              symbol: 'DOODLE',
              total_supply: '0',
              description:
                'A community-driven collectibles project featuring art by Burnt Toast. Doodles come in a joyful range of colors, traits and sizes with a collection size of 10,000. Each Doodle allows its owner to vote for experiences and activations paid for by the Doodles Community Treasury.',
              external_link: 'https://doodles.app',
              image_url: 'https://i.seadn.io/gae/7B0qai02OdHA8P_EOVK672qUliyjQdQDGNrACxs7WnTgZAkJa_wWURnIFKeOh5VTf8cfTqW3wQpozGedaC9mteKphEOtztls02RlWQ?w=500&auto=format',
              default_to_fiat: false,
              dev_buyer_fee_basis_points: 0,
              dev_seller_fee_basis_points: 500,
              only_proxied_transfers: false,
              opensea_buyer_fee_basis_points: 0,
              opensea_seller_fee_basis_points: 250,
              buyer_fee_basis_points: 0,
              seller_fee_basis_points: 750,
              payout_address: '0xd1f124cc900624e1ff2d923180b3924147364380'
            }
          ],
          traits: {
            face: {
              sunglasses: 694,
              'designer glasses': 662,
              '3d glasses': 203,
              'aviators with cig': 201,
              'in love': 647,
              happy: 744,
              straw: 411,
              'cobain glasses': 389,
              content: 646,
              'happy note': 164,
              grumpy: 685,
              surprised: 680,
              bandana: 378,
              'sad note': 170,
              default: 709,
              'pink beard': 137,
              mustache: 455,
              'chill cig': 557,
              'mad note': 121,
              'aviators with mustache': 153,
              'green beard': 174,
              'blue check': 123,
              'rainbow puke': 118,
              'puffer up': 22,
              'neutral note': 172,
              'blue beard': 157,
              skeleton: 166,
              'holographic beard': 129,
              'puffer up visor': 5,
              dino: 8,
              skelly: 1,
              'skelly cig': 11,
              mad: 6,
              '60s glasses': 22,
              shark: 12,
              bubblegum: 1,
              ape: 15,
              catnip: 1,
              'gold alien': 1,
              alien: 8,
              'holographic alien': 1,
              duck: 11,
              cat: 7,
              'satisfied ape': 1,
              whale: 4,
              'holographic visor': 6,
              stellar: 1,
              'pirate skelly': 1,
              'holographic cat': 1,
              'holographic dino': 3,
              'cat note': 1,
              'gold ape': 1,
              holographic: 1,
              'devil cat': 1,
              'holographic ape': 1,
              '3d glasses with cig': 1
            },
            hair: {
              'brown mullet': 282,
              'blue brushcut': 325,
              'blue messy': 250,
              pink: 250,
              'white bucket cap': 207,
              'purple long': 280,
              'pink headband': 263,
              'purple cap': 279,
              'yellow backwards cap': 186,
              'green brushcut': 264,
              'yellow headband': 293,
              'green puffballs': 302,
              cowboy: 172,
              'pink bucket cap': 212,
              'blue alfalfa': 283,
              'purple alfalfa': 271,
              'green mullet': 300,
              'purple brushcut': 265,
              'blue afro': 271,
              'green bowlcut': 302,
              'yellow toque': 187,
              'pink long': 279,
              'holographic crown': 33,
              shaved: 306,
              harley: 109,
              'blue nerd': 275,
              'blue puffballs': 263,
              'holographic bob': 39,
              'brown brushcut': 267,
              'purple puffballs': 284,
              'holographic brushcut': 65,
              'pink tidy': 256,
              'yellow bowlcut': 303,
              halo: 176,
              viking: 114,
              wizard: 74,
              'pink toque': 200,
              'blue mohawk': 296,
              'beige bucket cap': 200,
              'holographic afro': 90,
              helmet: 104,
              'holographic mohawk': 85,
              crown: 44,
              sailor: 34,
              'holographic poopie': 35,
              'blue toque': 170,
              'crown with holographic long': 17,
              'pink ape': 2,
              poopie: 61,
              'bubblegum bed head': 1,
              ape: 10,
              'green cat': 1,
              'gold alien': 1,
              'pink alien': 1,
              'blue alien': 1,
              'holographic alien': 2,
              'green ape': 2,
              'blue ape': 1,
              cat: 5,
              'grey alien': 1,
              'green alien': 2,
              'stellar bed head': 1,
              'holographic cat': 1,
              'gold bed head': 1,
              'rainbow mohawk': 2,
              'bed head': 1,
              'iridescent alien': 1,
              'private skelly': 1,
              'blue bucket cap': 1,
              'holographic bed head': 1,
              'devil cat': 1,
              'holographic ape': 1,
              'purple alien': 1
            },
            body: {
              'yellow backpack': 316,
              'white sweater': 354,
              'blue backpack': 298,
              'white puffer': 331,
              'purple chain': 112,
              'pink puffer': 313,
              'blue fleece': 301,
              'blue and yellow jacket': 281,
              'yellow puffer': 346,
              'green hoodie': 305,
              'purple sweater with satchel': 307,
              'light blue puffer': 308,
              'orange puffer': 322,
              'white turtleneck': 327,
              'combo 1 puffer': 331,
              'yellow turtleneck': 354,
              'orange collar': 323,
              'pink sweater with satchel': 323,
              'white collar': 289,
              'navy sweater': 326,
              'striped sweater': 298,
              'grey hoodie': 310,
              'green blazer': 119,
              'leopard hoodie': 67,
              'blue turtleneck': 313,
              'combo 3 puffer': 300,
              'blue blazer': 104,
              'pink and green jacket': 298,
              'combo 2 puffer': 300,
              'pink and white jacket': 337,
              'pink hoodie': 293,
              'pink backpack': 333,
              'holographic sweater': 40,
              'pink fleece': 317,
              'rainbow striped sweater': 55,
              'spotted hoodie': 54,
              skelly: 8,
              'spotted sweater': 51,
              'purple backpack': 1,
              'bubblegum sweater': 1,
              'green cat': 1,
              'gold alien': 1,
              alien: 8,
              'holographic alien': 1,
              cat: 9,
              'stellar sweater': 1,
              'brittle bones skelly': 1,
              'holographic cat': 1,
              'gold sweater': 1,
              'gold ape': 1,
              'gold chain': 1,
              'devil cat': 1,
              'holographic hoodie': 2,
              'holographic bone skelly': 1,
              'gold bone skelly': 1
            },
            background: {
              yellow: 703,
              'gradient 2': 664,
              grey: 742,
              iridescent: 436,
              blue: 726,
              purple: 692,
              green: 749,
              'light blue': 703,
              holographic: 341,
              'gradient 4': 691,
              'gradient 3': 653,
              space: 237,
              fire: 313,
              orange: 739,
              pink: 690,
              sky: 243,
              'gradient 1': 659,
              bubblegum: 1,
              'gold space': 1,
              'dark purple': 2,
              'pink space': 1,
              'blue space': 1,
              'holographic space': 1,
              gold: 3,
              'gradient space': 1,
              'grey space': 1,
              'green space': 1,
              'deeper space': 1,
              'starry blue': 1,
              'starry purple': 1,
              'dark grey': 1,
              'reverse gradient 1': 1,
              'deep space': 1
            },
            head: {
              pink: 970,
              purple: 934,
              pale: 936,
              yellow: 944,
              tan: 997,
              'gradient 2': 493,
              orange: 961,
              med: 952,
              blue: 1042,
              green: 983,
              'gradient 1': 458,
              pickle: 35,
              flower: 34,
              popsicle: 21,
              skelly: 14,
              devil: 43,
              coffee: 32,
              icecream: 17,
              rainbow: 26,
              'pink ape': 2,
              lit: 30,
              bubblegum: 1,
              ape: 12,
              'green cat': 1,
              'gold alien': 1,
              'green ape': 3,
              'pink alien': 1,
              'blue alien': 1,
              'holographic alien': 2,
              balloon: 31,
              cat: 8,
              'blue ape': 1,
              'calico cat': 1,
              'grey alien': 1,
              'green alien': 2,
              stellar: 1,
              'brittle bones skelly': 1,
              'holographic cat': 1,
              gold: 1,
              'iridescent alien': 1,
              'gold ape': 1,
              holographic: 1,
              'devil cat': 1,
              'holographic ape': 1,
              'purple alien': 1
            },
            piercing: {
              hoop: 1045,
              pearl: 1078,
              airpod: 515
            }
          },
          stats: {
            one_hour_volume: 7,
            one_hour_change: 0,
            one_hour_sales: 1,
            one_hour_sales_change: 0,
            one_hour_average_price: 7,
            one_hour_difference: 7,
            six_hour_volume: 7,
            six_hour_change: 0,
            six_hour_sales: 1,
            six_hour_sales_change: 0,
            six_hour_average_price: 7,
            six_hour_difference: 7,
            one_day_volume: 32.141999999999996,
            one_day_change: -0.6252234571031448,
            one_day_sales: 4,
            one_day_sales_change: -0.6,
            one_day_average_price: 8.035499999999999,
            one_day_difference: -53.621105,
            seven_day_volume: 432.4087849,
            seven_day_change: 0.3578029604916694,
            seven_day_sales: 58,
            seven_day_average_price: 7.455323877586207,
            seven_day_difference: 113.94668289999998,
            thirty_day_volume: 1661.499609899,
            thirty_day_change: 0.18018212193983948,
            thirty_day_sales: 224,
            thirty_day_average_price: 7.4174089727633925,
            thirty_day_difference: 253.66637889900016,
            total_volume: 154014.38236211875,
            total_sales: 24577,
            total_supply: 10000,
            count: 10000,
            num_owners: 5442,
            average_price: 6.2666062726174365,
            num_reports: 1,
            market_cap: 74553.23877586208,
            floor_price: 6.8
          },
          banner_image_url: 'https://i.seadn.io/gae/svc_rQkHVGf3aMI14v3pN-ZTI7uDRwN-QayvixX-nHSMZBgb1L1LReSg1-rXj4gNLJgAB0-yD8ERoT-Q2Gu4cy5AuSg-RdHF9bOxFDw?w=500&auto=format',
          chat_url: null,
          created_date: '2021-10-17T13:00:47.419945+00:00',
          default_to_fiat: false,
          description:
            'A community-driven collectibles project featuring art by Burnt Toast. Doodles come in a joyful range of colors, traits and sizes with a collection size of 10,000. Each Doodle allows its owner to vote for experiences and activations paid for by the Doodles Community Treasury.',
          dev_buyer_fee_basis_points: '0',
          dev_seller_fee_basis_points: '500',
          discord_url: 'https://discord.gg/doodles',
          display_data: {
            card_display_style: 'contain'
          },
          external_url: 'https://doodles.app',
          featured: false,
          featured_image_url: 'https://i.seadn.io/gcs/files/ad1e55ac8d380714566a3ecfe2a7dbcb.png?w=500&auto=format',
          hidden: false,
          safelist_request_status: 'verified',
          image_url: 'https://i.seadn.io/gae/7B0qai02OdHA8P_EOVK672qUliyjQdQDGNrACxs7WnTgZAkJa_wWURnIFKeOh5VTf8cfTqW3wQpozGedaC9mteKphEOtztls02RlWQ?w=500&auto=format',
          is_subject_to_whitelist: false,
          large_image_url: 'https://i.seadn.io/gae/svc_rQkHVGf3aMI14v3pN-ZTI7uDRwN-QayvixX-nHSMZBgb1L1LReSg1-rXj4gNLJgAB0-yD8ERoT-Q2Gu4cy5AuSg-RdHF9bOxFDw?w=500&auto=format',
          medium_username: null,
          name: 'Doodles',
          only_proxied_transfers: false,
          opensea_buyer_fee_basis_points: '0',
          opensea_seller_fee_basis_points: '250',
          payout_address: '0xd1f124cc900624e1ff2d923180b3924147364380',
          require_email: false,
          short_description: null,
          slug: 'doodles-official',
          telegram_url: null,
          twitter_username: 'doodles',
          instagram_username: null,
          wiki_url: null,
          is_nsfw: false,
          fees: {
            seller_fees: {
              '0xd1f124cc900624e1ff2d923180b3924147364380': 500
            },
            opensea_fees: {
              '0x0000a26b00c1f0df003000390027140000faa719': 250
            }
          },
          is_rarity_enabled: true
        }
      };
    }
  }
}
